-- 韩梦凯运营中心业务表（utf8mb4）。不要建 users / releases 等其他模块表。

CREATE TABLE IF NOT EXISTS han_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT '待办',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_brief (
  id TINYINT UNSIGNED NOT NULL,
  text MEDIUMTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_selection (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(512) NOT NULL,
  category VARCHAR(128) NOT NULL DEFAULT '',
  note VARCHAR(1024) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT '观察',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(512) NOT NULL,
  sku VARCHAR(128) NOT NULL DEFAULT '',
  price DECIMAL(12, 2) NULL,
  stock INT NULL,
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_paid (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  channel VARCHAR(128) NOT NULL,
  amount DECIMAL(12, 2) NULL,
  spent_on DATE NULL,
  note VARCHAR(1024) NOT NULL DEFAULT '',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_training (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(512) NOT NULL,
  trainee VARCHAR(128) NOT NULL DEFAULT '',
  scheduled_on DATE NULL,
  status VARCHAR(32) NOT NULL DEFAULT '待开始',
  note VARCHAR(1024) NOT NULL DEFAULT '',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
