-- 韩梦凯运营中心业务表（utf8mb4）。不要建 users / releases 等其他模块表。

CREATE TABLE IF NOT EXISTS han_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT '待办',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_brief (
  id TINYINT UNSIGNED NOT NULL,
  text MEDIUMTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
