-- 韩梦凯运营中心业务表（utf8mb4）。不要建 users / releases 等其他模块表。

CREATE TABLE IF NOT EXISTS han_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT '待办',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_brief (
  id TINYINT UNSIGNED NOT NULL,
  text MEDIUMTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_selection (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(512) NOT NULL,
  category VARCHAR(128) NOT NULL DEFAULT '',
  note VARCHAR(1024) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT '观察',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(512) NOT NULL,
  sku VARCHAR(128) NOT NULL DEFAULT '',
  price DECIMAL(12, 2) NULL,
  stock INT NULL,
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  layer VARCHAR(64) NOT NULL DEFAULT '',
  image_url VARCHAR(1024) NOT NULL DEFAULT '',
  spu VARCHAR(128) NOT NULL DEFAULT '',
  first_sku VARCHAR(128) NOT NULL DEFAULT '',
  hot_sell VARCHAR(256) NOT NULL DEFAULT '',
  review_count VARCHAR(64) NOT NULL DEFAULT '',
  share_count VARCHAR(64) NOT NULL DEFAULT '',
  qa_video VARCHAR(128) NOT NULL DEFAULT '',
  return_m5 VARCHAR(64) NOT NULL DEFAULT '',
  return_m6 VARCHAR(64) NOT NULL DEFAULT '',
  return_m7 VARCHAR(64) NOT NULL DEFAULT '',
  return_m8 VARCHAR(64) NOT NULL DEFAULT '',
  orders_30d VARCHAR(64) NOT NULL DEFAULT '',
  fulfill_note VARCHAR(256) NOT NULL DEFAULT '',
  jd_stock VARCHAR(64) NOT NULL DEFAULT '',
  listed_on DATE NULL,
  has_new_badge VARCHAR(32) NOT NULL DEFAULT '',
  need_order VARCHAR(256) NOT NULL DEFAULT '',
  remark VARCHAR(1024) NOT NULL DEFAULT '',
  team_name VARCHAR(64) NOT NULL DEFAULT '',
  spend_rate VARCHAR(64) NOT NULL DEFAULT '',
  gmv_7d VARCHAR(64) NOT NULL DEFAULT '',
  conv_rate VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_paid (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  channel VARCHAR(128) NOT NULL,
  amount DECIMAL(12, 2) NULL,
  spent_on DATE NULL,
  note VARCHAR(1024) NOT NULL DEFAULT '',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_training (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(512) NOT NULL,
  trainee VARCHAR(128) NOT NULL DEFAULT '',
  scheduled_on DATE NULL,
  status VARCHAR(32) NOT NULL DEFAULT '待开始',
  note VARCHAR(1024) NOT NULL DEFAULT '',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_team_shops (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  team_name VARCHAR(64) NOT NULL,
  store_name VARCHAR(128) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_shop_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  team_name VARCHAR(64) NOT NULL,
  store_name VARCHAR(128) NOT NULL,
  rules_json MEDIUMTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_han_shop_rules (team_name, store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_shop_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  team_name VARCHAR(64) NOT NULL,
  store_name VARCHAR(128) NOT NULL,
  month_plan MEDIUMTEXT NOT NULL,
  week_plan MEDIUMTEXT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_han_shop_plans (team_name, store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS han_picks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  board VARCHAR(32) NOT NULL,
  name VARCHAR(512) NOT NULL,
  extra VARCHAR(256) NOT NULL DEFAULT '',
  category VARCHAR(128) NOT NULL DEFAULT '',
  note VARCHAR(1024) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT '观察',
  owner VARCHAR(64) NOT NULL DEFAULT '韩梦凯',
  store_name VARCHAR(128) NOT NULL DEFAULT '韩梦凯店',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
