CREATE TABLE IF NOT EXISTS release_tickets (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  version VARCHAR(128) NOT NULL,
  applicant VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  module VARCHAR(64) NOT NULL,
  summary TEXT NOT NULL,
  files JSON NOT NULL,
  acceptance TEXT NULL,
  restart TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  priority INT NOT NULL,
  demo TINYINT(1) NOT NULL DEFAULT 0,
  submitted_at DATETIME(3) NOT NULL,
  reviewer VARCHAR(128) NULL,
  reviewed_at DATETIME(3) NULL,
  reject_reason TEXT NULL,
  publish_started_at DATETIME(3) NULL,
  publish_finished_at DATETIME(3) NULL,
  log TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_release_tickets_status_priority (status, priority, submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
